### PR TITLE
modify oasim to run with ufo

### PR DESCRIPTION
**Pull request by HamidehGMAO**
## Description

I modified oasim a little bit to make it work with the https://github.com/JCSDA-internal/ufo/tree/feature/oasim_run, having a subroutine named "delete" in both ufo and oasim was causing error, I renamed it here to "cancel" to resolve the issue, but I'm open to suggestions. also the subroutine lidata was commented here after discussion with Cecile it turned out it should be uncommented

### Issue(s) addressed

this is needed for the issue "hookup non-linear part of OASIM  #2169"

I

### CODE REVIEW

**Review by travissluka — CHANGES_REQUESTED** [review]
i would leave this repo the way it is. Instead modify the `ufo_oasim` class to contain a member variable of this `oasim` class, and NOT use `extend` to make `ufo_oasim` a subclass of `oasim`. Making it a subclass makes maintainability more difficult due to thing such as name conflicts, as you have seen

**Comment by HamidehGMAO** [comment]
I did try renaming the ufo-oasim before, but still I had issues, I think it was because the procedure delete is defined here https://github.com/JCSDA-internal/ufo/blob/84510f204d86dc20a8a272d2c5864def202ffab1/src/ufo/operators/oasim/ufo_oasim_mod.F90#L34

**Comment by travissluka** [comment]
@HamidehGMAO The allocation and initialization of `phyto` here https://github.com/JCSDA-internal/oasim/blob/develop/src/oasim/oasim_mod.f90#L168-L174 is wrong.
- `lm` is not initialized before it is used, and `ntyp != km`, so `shape(phyto)` is `0,19` but `shape(diatom)` is `14`, which is causing memory corruption when you are trying to do the assignment.

**Comment by travissluka** [comment]
> @HamidehGMAO The allocation and initialization of `phyto` here https://github.com/JCSDA-internal/oasim/blob/develop/src/oasim/oasim_mod.f90#L168-L174 is wrong.
> 
> * `lm` is not initialized before it is used, and `ntyp != km`, so `shape(phyto)` is `0,19` but `shape(diatom)` is `14`, which is causing memory corruption when you are trying to do the assignment.

maybe the allocation line is supposed to be `allocate(phyto(km,nchl))` ?

**Comment by HamidehGMAO** [comment]
Ah! you are right! Thanks a lot for looking into this. I've been going crazy.

**Comment by travissluka** [comment]
`call glight(lm ,...` should be `call glight(km, ...`  at
https://github.com/JCSDA-internal/oasim/blob/5b262b6e9e56b9dc2638bb59da6bbe54dea7eb98/src/oasim/oasim_mod.f90#L219
remove that `lm` variable, it's obviously not used

**Comment by travissluka** [comment]
There is something wrong with the initialization of `avgq`. 
It is used in two places without having been first initialized to anything
* https://github.com/JCSDA-internal/oasim/blob/5b262b6e9e56b9dc2638bb59da6bbe54dea7eb98/src/oasim/daysetrad_mod.f90#L40
* https://github.com/JCSDA-internal/oasim/blob/5b262b6e9e56b9dc2638bb59da6bbe54dea7eb98/src/oasim/edeu_mod.f90#L165

**Comment by travissluka** [comment]
`bbrw` is used without having been first initialized to anything, here 
https://github.com/JCSDA-internal/oasim/blob/5b262b6e9e56b9dc2638bb59da6bbe54dea7eb98/src/oasim/edeu_mod.f90#L137

**Comment by travissluka** [comment]
a floating point exception is occurring here
https://github.com/JCSDA-internal/oasim/blob/5b262b6e9e56b9dc2638bb59da6bbe54dea7eb98/src/oasim/radmod_mod.f90#L106
when `zd` gets set to `-9999` somewhere higher up in the code

**Review by travissluka — APPROVED** [review]

**Comment by travissluka** [comment]
@HamidehGMAO the related UFO PR is working now for me :tada: 
Is this PR ready to merge?

**Comment by HamidehGMAO** [comment]
> @HamidehGMAO the related UFO PR is working now for me 🎉 Is this PR ready to merge?

Yes @travissluka , we can merge this! Thanks

**Pull request merged**
